### ISSUE TITLE
php artisan migrate报错

### ISSUE THREAD

**Issue by Turing2008** [nosoxo/MyNav#1]
# php artisan migrate
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table

   Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_name_unique`(`name`))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:692
    688▕         // If an exception occurs when attempting to run a query, we'll format the error
    689▕         // message to include the bindings with SQL, which will make this exception a
    690▕         // lot more helpful to the developer instead of just the database's errors.
    691▕         catch (Exception $e) {
  ➜ 692▕             throw new QueryException(
    693▕                 $query, $this->prepareBindings($bindings), $e
    694▕             );
    695▕         }
    696▕ 

      +9 vendor frames 
  10  database/migrations/2014_10_12_000000_create_users_table.php:27
      Illuminate\Support\Facades\Facade::__callStatic()

      +21 vendor frames 
  32  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by nosoxo** [comment]
可参考
https://stackoverflow.com/questions/23786359/laravel-migration-unique-key-is-too-long-even-if-specified

use Illuminate\Database\Schema\Builder;
public function boot()
{
    Builder::defaultStringLength(191);
}

**Comment by nosoxo** [comment]
laravel8 需要 MySQL5.7+
